### ISSUE TITLE
Message ( I also asked this on curseforge but I remembered that you said it was a bad place to ask you something)

### ISSUE THREAD

**Issue by levilips123** [Thutmose/ThutWearables#5] opened 2018-07-09 14:11 UTC
hey ThutMose . I want to ask you something . about your thut wearables mod. maybe you don't care about that anymore . but if you do, I think I figured out how you can make the baubles from botania to work in you slots 100%. and probably any item that works as a bauble . you could make your slots to have the same code like the slots from baubles . how should i explain it ..... the belt slot from your mod to be a belt slot from baubles . the ring slots to be ring slots from baubles , etc . if you could and want me to explain it further to you , how can i contact you ? skype or discord . I have this request because I want to make a big modpack that has a lot of baubles and i would like to have as many as I can since some are very needed for further game and this is the reason I want your mod in my modpack too . I also hope that you did not abandon this mod . thank you for giving time to read this.

**Comment by Thutmose** [comment] 2018-07-14 19:30
duplicate of #4

**Closed as completed by Thutmose** 2018-07-14 19:30 UTC
